"""Initial migration.

Revision ID: 03e300673dd8
Revises: 
Create Date: 2023-02-15 16:37:24.874548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03e300673dd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('imc', sa.Float(), nullable=True),
    sa.Column('percentual_gordura', sa.Float(), nullable=True),
    sa.Column('percentual_massa', sa.Float(), nullable=True),
    sa.Column('efumante', sa.Boolean(), nullable=True),
    sa.Column('ehipertenso', sa.Boolean(), nullable=True),
    sa.Column('ediabetico', sa.Boolean(), nullable=True),
    sa.Column('pratica_atividade', sa.Boolean(), nullable=True),
    sa.Column('problemas_coluna', sa.Boolean(), nullable=True),
    sa.Column('tratamento_osseo', sa.Boolean(), nullable=True),
    sa.Column('tontura_frequente', sa.Boolean(), nullable=True),
    sa.Column('valor_fuzzy', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pertinencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imc_baixo', sa.Float(), nullable=True),
    sa.Column('imc_medio', sa.Float(), nullable=True),
    sa.Column('imc_alto', sa.Float(), nullable=True),
    sa.Column('percentual_gordura_baixo', sa.Float(), nullable=True),
    sa.Column('percentual_gordura_medio', sa.Float(), nullable=True),
    sa.Column('percentual_gordura_alto', sa.Float(), nullable=True),
    sa.Column('percentual_massa_baixo', sa.Float(), nullable=True),
    sa.Column('percentual_massa_medio', sa.Float(), nullable=True),
    sa.Column('percentual_massa_alto', sa.Float(), nullable=True),
    sa.Column('efumante', sa.Boolean(), nullable=True),
    sa.Column('ediabetico', sa.Boolean(), nullable=True),
    sa.Column('ehipertenso', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regra_portuges', sa.String(), nullable=True),
    sa.Column('regra_fuzzy', sa.String(), nullable=True),
    sa.Column('treino', sa.String(), nullable=True),
    sa.Column('tempo', sa.Integer(), nullable=True),
    sa.Column('imc', sa.Boolean(), nullable=True),
    sa.Column('percentual_gordura', sa.Boolean(), nullable=True),
    sa.Column('percentual_massa', sa.Boolean(), nullable=True),
    sa.Column('efumante', sa.Boolean(), nullable=True),
    sa.Column('ediabetico', sa.Boolean(), nullable=True),
    sa.Column('ehipertenso', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('treinos', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('eadmin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aluno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('genero', sa.String(), nullable=True),
    sa.Column('usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('genero', sa.String(), nullable=True),
    sa.Column('usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professor')
    op.drop_table('aluno')
    op.drop_table('usuario')
    op.drop_table('treino')
    op.drop_table('regra')
    op.drop_table('pertinencia')
    op.drop_table('avaliacao')
    # ### end Alembic commands ###
