"""Corrigido relacionamento do Aluno com o Treino

Revision ID: 0cced181190c
Revises: 4d403779ada5
Create Date: 2023-02-16 10:24:22.372835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cced181190c'
down_revision = '4d403779ada5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treino', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aluno', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'aluno', ['aluno'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('treino', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('aluno')

    # ### end Alembic commands ###
