"""Removido Colunas tabela pertinencia

Revision ID: 5c50fb06b698
Revises: 0cced181190c
Create Date: 2023-02-17 11:08:02.897636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c50fb06b698'
down_revision = '0cced181190c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pertinencia', schema=None) as batch_op:
        batch_op.drop_column('ediabetico')
        batch_op.drop_column('ehipertenso')
        batch_op.drop_column('efumante')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pertinencia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('efumante', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ehipertenso', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ediabetico', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
