"""Corrigido nome da coluna regra_portugues da tabela Regra

Revision ID: f1ed7d199c24
Revises: 8bde99f12ea0
Create Date: 2023-02-20 17:10:43.103206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1ed7d199c24'
down_revision = '8bde99f12ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regra_portugues', sa.String(), nullable=True))
        batch_op.drop_column('regra_portuges')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('regra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regra_portuges', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('regra_portugues')

    # ### end Alembic commands ###
